language: java

before_install:
  - wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz
  - tar xzf apache-ant-1.9.4-bin.tar.gz
  - wget -O jacoco-0.7.5.zip http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.5.201505241946/jacoco-0.7.5.201505241946.zip
  - unzip -d jacoco-0.7.5 jacoco-0.7.5.zip

addons:
  apt:
    packages:
    - junit4

install: true

script: apache-ant-1.9.4/bin/ant -lib /usr/share/java/junit4.jar -lib jacoco-0.7.5/lib clean all test

jdk:
  - oraclejdk8
